stages:
  - build

build:
  stage: build
  image: "rust:latest"
  script:
    - cargo build --target x86_64-unknown-linux-gnu --release
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/pizarra
