stages:
  - build
  - deploy

build:
  stage: build
  image: categulario/pizarra-ci-builds:1.0.1
  variables:
    VERSION: ${CI_COMMIT_TAG:1}.$CI_COMMIT_SHORT_SHA
    ARCH: x86_64
    ARCHIVENAME: pizarra-$VERSION-$ARCH.tar.gz
  script:
    # build the binary
    - cargo build --locked --release
    # create the tar package
    - mkdir -p build
      # move things to the build directory
    - cp target/release/pizarra build/pizarra
    - cp res/icons/tk.categulario.pizarra.svg build/pizarra.svg
    - cp res/pizarra.desktop build/pizarra.desktop
    - cp CHANGELOG.md build/CHANGELOG.md
    - cp README.md build/README.md
    - cp LICENSE build/LICENSE
      # compress the tar file
    - tar -cvzf $ARCHIVENAME build/
      # makes the debian archive
    - ./debpackage.sh
  artifacts:
    paths:
      - $ARCHIVENAME
      - debian-package/pizarra_${VERSION}_amd64.deb
  only:
    - tags
