[package]
name = "pizarra-gtk"
version = "0.1.0"
authors = ["Abraham Toriz <categulario@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.12.0"
glib = "0.9.3"
pizarra = { git = "https://gitlab.com/categulario/pizarra.git", branch = "feature/separate-crates" }

[dependencies.cairo-rs]
version = "0.8.1"
features = ["svg", "png"]

[dependencies.gtk]
version = "0.8.1"
features = ["v3_22"]

[dependencies.gio]
version = ""
features = ["v2_44"]
