[package]
name = "pizarra"
description = "Tu pizarrón virtual de confianza"
documentation = "https://pizarra.categulario.tk"
homepage = "https://pizarra.categulario.tk"
repository = "https://gitlab.com/categulario/pizarra-gtk"
license-file = "LICENSE"
edition = "2018"
authors = ["Abraham Toriz <categulario@gmail.com>"]
version = "1.3.1"

[dependencies]
gdk = "0.13"
glib = "0.10"
pizarra = "1.1"
simple_logger = "1.13.0"

[dependencies.cairo-rs]
version = "0.9"
features = ["svg", "png"]

[dependencies.gtk]
version = "0.9"
features = ["v3_22"]

[dependencies.gio]
version = "0.9"
features = ["v2_44"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
