[package]
name = "pizarra"
edition = "2018"
authors = ["Abraham Toriz <categulario@gmail.com>"]
version = "1.3.0"

[dependencies]
gdk = "0.13"
glib = "0.10"
pizarra = "0.9.3"

[dependencies.cairo-rs]
version = "0.9"
features = ["svg", "png"]

[dependencies.gtk]
version = "0.9"
features = ["v3_22"]

[dependencies.gio]
version = "0.9"
features = ["v2_44"]
