[package]
name = "pizarra"
edition = "2018"
authors = ["Abraham Toriz <categulario@gmail.com>"]
version = "1.1.0"

[dependencies]
gdk = "0.12.0"
glib = "0.9.3"
pizarra = "0.8"

[dependencies.cairo-rs]
version = "0.8.1"
features = ["svg", "png"]

[dependencies.gtk]
version = "0.8.1"
features = ["v3_22"]

[dependencies.gio]
version = ""
features = ["v2_44"]
